Cost time optimization for Loudness Zwicker
Eomys/MoSQITo pull request #39
Opened 2022-02-18 15:13 UTC by ErnestoAvedillo

With this pull request, I modify several files with the objective to improve the speed of the loudness calculation.
In general terms, instead of calculating with values, I propose to work with arrays or vectors when not possible with arrays.
Some of the changes have modified the complete routine and have been quite hard to develop. 
They are not even intuitive so will require some clarification from my side. I would propose to document this change in your folder documentation with an explanation of those routines.
All tests have passed in my version, so they should pass in your system too but would be recommended to be reviewed from your side.
I also would like your collaborators to verify the results with the audios they have, when possible, and if they don't match, please send some feedback to correct the possible discrepancies.

2022-02-18 16:34 UTC, mglesser commented
Hello Ernesto, thanks a lot for this contribution. I will try to review it soon. I will let you know.

2022-02-18 18:50 UTC, ErnestoAvedillo commented
Hello Martin
Thanks for your feedback.

This exercise has been a challenge for me and I am excited to know how it
works by you.

I compared both versions of the code with one audio file, and while the
current needs 350 seconds of running time, the one I generated took 7
seconds only.

I am worried I did something wrong because I can't believe this difference.

Hope hearing you soon.
Thanks for all.
Best regards.

Ernesto



El vie., 18 feb. 2022 17:34, Martin Glesser ***@***.***>
escribió:

> Hello Ernesto, thanks a lot for this contribution. I will try to review it
> soon. I will let you know.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Eomys/MoSQITo/pull/39#issuecomment-1044800186>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASOLUYN2HVJ7AH7JRAHFRJDU3ZYJPANCNFSM5OYGUWXQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-02-22 12:27 UTC, mglesser requested changes
Hi Ernesto, thanks a lot for this contribution. I've runned the tests and validations successfully. I've just suggested a few minor modifications before the merge. Don't hesitate to contact me if you want to discuss them.

2022-02-22 12:29 UTC, mglesser commented
Your implementation even solved an issue we had for one of the test signals from the ISO ! That's wonderfull !

2022-02-22 18:25 UTC, ErnestoAvedillo commented on tests/sharpness/test_sharpness.py
> +    print ("S_Value is ", str(S))
Ups sorry I shouldn't have committed this change.

2022-02-22 18:25 UTC, ErnestoAvedillo commented on validations/loudness_zwicker/validation_loudness_zwicker_stationary.py
> +    print ("My N is ",str(N), " N_iso_ref is ", str(N_iso))
Same as before.
Is my mistake.

2022-02-22 18:27 UTC, ErnestoAvedillo commented on mosqito/functions/loudness_zwicker/loudness_zwicker_shared.py
> -    # Ref. ISO 532-1:2017 paragraph A.3
I don't remember having deleted this test.
Could have been a mistake.

2022-02-22 18:29 UTC, ErnestoAvedillo commented
I am proud to hear this.
Thank you very much.

2022-02-24 10:42 UTC, merged