Roughness ECMA 418-2
Eomys/MoSQITo pull request #64
Opened 2023-07-25 07:21 UTC by wantysal

New version of roughness calculation according to ECMA 418-2.
The code uses Sottek's Hearing Model implemented in loudness_ecma. The final roughness values are not validated yet due to some weighting errors.

2024-04-02 10:35 UTC, wantysal commented
Thanks to a collaboration with @fchirono the code has been updated and the model now seems very close to the ECMA 418-2 results. Validation plots have been created :
![roughness_validation](https://github.com/Eomys/MoSQITo/assets/70269666/82c3ccd1-e7c2-4986-99a1-04b3395fb715)
And all tests are running:
![image](https://github.com/Eomys/MoSQITo/assets/70269666/5dc8aa7c-433d-4f3d-be20-0b4ecc78ded5)

2024-04-04 07:57 UTC, fchirono commented
Excellent work Salomé, the new validation results look great! 😃

2024-04-16 07:01 UTC, mglesser requested changes
I made 2 minor comments directly in the files. I'm also wondering if we shouldn't take the occasion of this release to remove the tutorials that are probably outdated now. And maybe also to simmplify the main readme with a link to the documentation website.

2024-04-16 09:05 UTC, fchirono commented on mosqito/sq_metrics/roughness/roughness_ecma/_von_hann_window.py
The ECMA 418-2 standard specifies a normalised version of the Hann window, with the extra `sqrt(0.375)` factor when compared to the SciPy (or identical Numpy) version. My personal opinion is that it is worth having it as a separate, explicit function to emphasize it differs from the usual definition, but this is not something I feel too strongly about it - I'm happy either way.

2024-04-17 14:45 UTC, wantysal commented
Hi @mglesser,

Requested changes have been made ;)

Tks for your review

2024-04-18 15:06 UTC, merged